### ISSUE TITLE
feature(组件库规范问题):  组件库key value 命名规范问题

### ISSUE THREAD

**Issue by zhoulujun** [TencentBlueKing/bkui-vue3#1046]
slelect 取值为label 、value
Cascader   searchSelet 、tree为name、id
table的筛选项  为 text 、value
tab 为label name 
等等……
需要转换，或者设置idkey 等，希望统一
比如：
![image](https://github.com/TencentBlueKing/bkui-vue3/assets/4243366/e371bf1e-2a02-4287-b1e8-f7e86bf39863)
表格的选项值回填到searchSelect ，就需要变换key

**Comment by HubuHito** [comment]
全部统一成 { id: xxx, name: xxx }
