### ISSUE TITLE
bugfix(select): 搜索出了问题

### ISSUE THREAD

**Issue by zhoulujun** [TencentBlueKing/bkui-vue3#1157]
**Version / Branch / tag**

**出了什么问题？(What Happened?)**
![image](https://github.com/TencentBlueKing/bkui-vue3/assets/4243366/3143681d-bd97-4515-a102-fb16bbd75db7)

**如何复现？(How to reproduce?)**
https://bkui-vue.woa.com/select

**预期结果(What you expect?)**
模糊高亮搜索，支持拼音

**Comment by ielgnaw** [comment]
@HubuHito
