### ISSUE TITLE
bugfix(slider): 滑动label上方的tip数值始终是0

### ISSUE THREAD

**Issue by jinquantianxia** [TencentBlueKing/bkui-vue3#1180]
如图：
<img width="681" alt="企业微信截图_16923431467831" src="https://github.com/TencentBlueKing/bkui-vue3/assets/22766131/244c3dde-2eb0-4e5e-9452-98371fce6af0">
不管怎么设置，formatLabel，始终是显示0，文档给的demo也是这种情况

**Comment by ielgnaw** [comment]
好了

bkui-vue@0.0.2-beta.14
