### ISSUE TITLE
feature(table):  支持activeSortIndex参数初始化

### ISSUE THREAD

**Issue by GONGONGONG** [TencentBlueKing/bkui-vue3#1201]
![image](https://github.com/TencentBlueKing/bkui-vue3/assets/29882448/852f4154-9781-4e31-beea-8f6033c0001f)

**Comment by GONGONGONG** [comment]
![image](https://github.com/TencentBlueKing/bkui-vue3/assets/29882448/629da244-1627-4748-a2aa-349da3b21f42)

**Comment by brookylin** [comment]
组件库提供排序方法
