### ISSUE TITLE
bugfix(resize-layout): 嵌套场景下collaps按钮收齐/展开异常

### ISSUE THREAD

**Issue by jinquantianxia** [TencentBlueKing/bkui-vue3#1213]
当嵌套使用resize-layout组件时，点击外层的collaps收齐按钮，会连带收齐内部设置了collapsible为true的区域，反过来也是

如图：
![image](https://github.com/TencentBlueKing/bkui-vue3/assets/22766131/4466a004-613f-4a5e-a802-dc3452be6571)

**Comment by HubuHito** [comment]
已经沟通，代码样式覆盖问题
