### ISSUE TITLE
bugfix(tooltips):如果只引入tooltips指令，样式不存在。 

### ISSUE THREAD

**Issue by zhoulujun** [TencentBlueKing/bkui-vue3#1218]
**Version / Branch / tag**

**出了什么问题？(What Happened?)**
![image](https://github.com/TencentBlueKing/bkui-vue3/assets/4243366/a6bac62f-dd45-4e56-ae0f-3f364d4bafe4)

**如何复现？(How to reproduce?)**
git+https://github.com/zhoulujun/monaco-vue3.git

**预期结果(What you expect?)**

**Comment by ielgnaw** [comment]
单独引入组件的时候，每个组件的样式需要引入依赖的样式，在 css 中引入
