### ISSUE TITLE
bugfix(table): 表头使用render函数，设置minWidth。开启虚拟滚动，滚动后，数据还是之前的数据 

### ISSUE THREAD

**Issue by zhoulujun** [TencentBlueKing/bkui-vue3#1284]
**Version / Branch / tag**

**出了什么问题？(What Happened?)**
![image](https://github.com/TencentBlueKing/bkui-vue3/assets/4243366/963fa3df-488c-4ce3-a703-0883ed825090)

**如何复现？(How to reproduce?)**
![image](https://github.com/TencentBlueKing/bkui-vue3/assets/4243366/c2ed8daf-c02a-479f-85cb-d476ed4d4903)

**预期结果(What you expect?)**

**Comment by xintaoLi** [comment]
![image](https://github.com/TencentBlueKing/bkui-vue3/assets/9812285/a7436191-7e05-4150-8d52-7addad27bcf7)
