### ISSUE TITLE
bugfix(tab): panel数量过多，超出容器宽度后会被隐藏

### ISSUE THREAD

**Issue by 3octaves** [TencentBlueKing/bkui-vue3#1392]
**出了什么问题？(What Happened?)**

![image](https://github.com/TencentBlueKing/bkui-vue3/assets/109950386/c1e25a57-9506-4703-bba2-279c2ab774ad)

**预期结果(What you expect?)**

 超出后能有滚动条，让用户能选择到被隐藏的项目

**Comment by ielgnaw** [comment]
现在是可以滚动的
