### ISSUE TITLE
bugfix(select): 虚拟滚动使用optionRender函数，搜索后清空搜索，虚拟列表加载不全

### ISSUE THREAD

**Issue by zhoulujun** [TencentBlueKing/bkui-vue3#1414]
**Version / Branch / tag**

**出了什么问题？(What Happened?)**

正常的
![image](https://github.com/TencentBlueKing/bkui-vue3/assets/4243366/7733139a-521f-4443-bf54-431fb32db69d)
搜索
![image](https://github.com/TencentBlueKing/bkui-vue3/assets/4243366/cc4faf03-4cad-4b13-8109-c3b946d91653)
取消后
![image](https://github.com/TencentBlueKing/bkui-vue3/assets/4243366/ebff45cc-dd14-4b39-8def-2f7af65ea46d)

**如何复现？(How to reproduce?)**
代码案例，联系我

**预期结果(What you expect?)**

**Comment by ielgnaw** [comment]
@HubuHito
