### ISSUE TITLE
bugfix(tree):  tree组件子级全部勾选的情况下依然展示半选

### ISSUE THREAD

**Issue by byronbyyuan** [TencentBlueKing/bkui-vue3#1430]
![image](https://github.com/TencentBlueKing/bkui-vue3/assets/28644705/1315af0d-a395-4ae8-8f0e-625f659e9212)

操作路径

1. 先全部勾选
2. 取消其中一个子级
3. 再次点击全部勾选
4. 父级展示为半选状态，子级是全部勾选的

**Comment by ielgnaw** [comment]
待确认
