### ISSUE TITLE
bugfix(tag-input): 

### ISSUE THREAD

**Issue by zhoulujun** [TencentBlueKing/bkui-vue3#1432]
**Version / Branch / tag**

如果复制的字符中带有 -，粘贴时就会被截断
**出了什么问题？(What Happened?)**
![image](https://github.com/TencentBlueKing/bkui-vue3/assets/4243366/a577ad06-5154-4aac-9a83-42dba6a8e32c)

![image](https://github.com/TencentBlueKing/bkui-vue3/assets/4243366/6712da9e-2a8e-415e-8c37-d32451f126ce)

**如何复现？(How to reproduce?)**

将这个字符 abcd-efg 复制粘贴过去，即可发现只有 abcd 有效，横杠及其后面的字符被截断了
**预期结果(What you expect?)**

**Comment by ielgnaw** [comment]
默认的 paste-fn 是在这里 
https://github.com/TencentBlueKing/bkui-vue3/blob/staging/packages/tag-input/src/tag-input.tsx#L664
这里的确是做了个正则截取，如果想要自定义复制的 function，参考下列实例

https://magicbox.bk.tencent.com/magicbox/3.0/tag-input

<img width="1628" alt="image" src="https://github.com/TencentBlueKing/bkui-vue3/assets/1153430/4d0a5df2-2351-43e6-9e50-2d8138dfe98f">
