### ISSUE TITLE
bugfix(popconfirm): class加不上

### ISSUE THREAD

**Issue by coder-cwc** [TencentBlueKing/bkui-vue3#1457]
**Version / Branch / tag**
"bkui-vue": "0.0.2-beta.103",

**出了什么问题？(What Happened?)**
![image](https://github.com/TencentBlueKing/bkui-vue3/assets/147811460/7b1571dc-dedf-4ada-bed3-c58a001676b1)

**如何复现？(How to reproduce?)**

**预期结果(What you expect?)**

**Comment by coder-cwc** [comment]
![image](https://github.com/TencentBlueKing/bkui-vue3/assets/147811460/d1e32c22-cb0d-489e-887a-47d963a8b6c5)
内联样式也写不上

**Comment by ielgnaw** [comment]
ext-cls
