### ISSUE TITLE
bugfix(pop-confirm): content设置为jsx报warn

### ISSUE THREAD

**Issue by jinquantianxia** [TencentBlueKing/bkui-vue3#1461]
content是支持传入function的，但是类型定义不对导致框架校验报警
![image](https://github.com/TencentBlueKing/bkui-vue3/assets/22766131/cca19d13-fd01-4d8a-9416-a966f3d5035b)

**Comment by ielgnaw** [comment]
bkui-vue@0.0.2-beta.122
