### ISSUE TITLE
bugfix(checkbox): 不管是设置model-value还是v-model都无法做到由数据去设置勾选状态

### ISSUE THREAD

**Issue by jinquantianxia** [TencentBlueKing/bkui-vue3#1462]
始终跟着勾选行为去自动设置勾选状态，可以参考switcher的model-value，不受点击动作影响，当model-value对应的变为真，才显示开启状态，反之关闭状态

**Comment by hLinx** [comment]
目前交互逻辑正常，需求应该是加一个值改变的前置校验
