### ISSUE TITLE
feature(bk-input): bk-input 组件支持 ctrl-z 回撤输入 

### ISSUE THREAD

**Issue by zhanxu33** [TencentBlueKing/bkui-vue3#1485]
bk-input 在 textarea模式下，如果使用 v-molde 修改值，无法使用 ctrl-z 回撤输入 
 复现链接：https://stackblitz.com/edit/jmpv3s?file=src%2Fdemo.vue

**Comment by ielgnaw** [comment]
组件没法知道是直接修改还是通过 v-model 修改，这个应该业务自己实现，调用者通过 v-model 改变值的时候本身是知道这个逻辑的
