### ISSUE TITLE
feature(tooltips): 是否可以支持 html

### ISSUE THREAD

**Issue by coder-cwc** [TencentBlueKing/bkui-vue3#1503]
代码: 
![image](https://github.com/TencentBlueKing/bkui-vue3/assets/147811460/ef85a30d-7a34-4745-8a1a-512f7157c3b7)

实际效果:
![image](https://github.com/TencentBlueKing/bkui-vue3/assets/147811460/13c838d6-c34a-4cd4-9ed4-3b5bec9c4954)

期望: 链接可以点击跳转

**Comment by lhzzforever** [comment]
@coder-cwc <img width="763" alt="企业微信截图_9d525f9f-0b48-46f2-b9e4-c6fb2eb3d3c8" src="https://github.com/user-attachments/assets/91982705-1ff4-4aa4-97e2-5d2d165079e3">
