### ISSUE TITLE
bugfix(tooltips): showOnInit选项不生效

### ISSUE THREAD

**Issue by DI404N** [TencentBlueKing/bkui-vue3#1523]
**出了什么问题？(What Happened?)**
设置showOnInit为true后不生效，并且鼠标悬浮后，有函数循环引用，爆栈了
<img width="903" alt="image" src="https://github.com/TencentBlueKing/bkui-vue3/assets/71928548/30749c66-c63f-485a-9867-eab3c8da39cf">
![image](https://github.com/TencentBlueKing/bkui-vue3/assets/71928548/bb12a0f6-77a2-4c2c-adde-f005003b21e4)

**Comment by ielgnaw** [comment]
bkui-vue@2.0.1-beta.58
