### ISSUE TITLE
bugfix(tree): disabled-folder-selectable配置不生效

### ISSUE THREAD

**Issue by brookylin** [TencentBlueKing/bkui-vue3#1572]
**Version / Branch / tag**

**出了什么问题？(What Happened?)**

tree组件，disabled-folder-selectable值设为true，还是可以选择非叶子节点

应该是resolvedItem没有is_folder属性了

<img width="759" alt="image" src="https://github.com/TencentBlueKing/bkui-vue3/assets/23353690/58d481ea-466c-4dc3-aff5-9238cdd95a81">

**预期结果(What you expect?)**

**Comment by xintaoLi** [comment]
传递的数据需要显示告知是否为 is_folder
[
  {
    id: '1',
    name: 'node1',
    is_folder: true,
  }
]
