### ISSUE TITLE
bugfix(dialog): transfer 属性失效 

### ISSUE THREAD

**Issue by forrany** [TencentBlueKing/bkui-vue3#1673]
**Version / Branch / tag**

**出了什么问题？(What Happened?)**
在 #1567 中，`trsanfer`属性的修改被修改错误，导致原逻辑受到影响。

在最初逻辑中，trasnfer 支持`boolean | string | HtmlElement` 

其中 如果是 boolean:
  ture: 表示移动到 body 下
  false: 表示保持原结构

string 支持 `parent` 

<img width="2269" alt="image" src="https://github.com/TencentBlueKing/bkui-vue3/assets/29779326/a09d6e05-20b5-4a10-8fe1-e2fb5688dfb0">

新的修改导致上面的逻辑失效

<img width="833" alt="image" src="https://github.com/TencentBlueKing/bkui-vue3/assets/29779326/b304ea32-5094-4ae6-bbdd-621edaec9be3">

**如何复现？(How to reproduce?)**

**预期结果(What you expect?)**

**Comment by ielgnaw** [comment]
bkui-vue@2.0.1-beta.64
