### ISSUE TITLE
bugfix(pop-confirm): 与Select组件一起使用时，Change事件会导致整个pop-confirm一起关闭

### ISSUE THREAD

**Issue by jinquantianxia** [TencentBlueKing/bkui-vue3#1690]
看源码很大可能是 Option点击事件 handleOptionSelected 中触发的 hidePopover事件导致的 Bug，希望这周内能尽快处理，线上环境急用。

**Comment by ielgnaw** [comment]
@HubuHito

**Comment by ielgnaw** [comment]
<img width="513" alt="企业微信截图_4dd3f71e-f7ca-4a89-93ba-c041f026f083" src="https://github.com/TencentBlueKing/bkui-vue3/assets/1153430/35599872-0426-44cb-b99a-0b248d60d62b">

先加个 boundary，因为两个 popover 都挂载到 body，统一层级，点击里面的会触发 clickoutside，后面再想办法
