### ISSUE TITLE
bugfix(Sideslider): 打开Sideslider后控制台一直报from model content size change

### ISSUE THREAD

**Issue by royalpioneer** [TencentBlueKing/bkui-vue3#1726]
**Version / Branch / tag**
1.0.3-beta.49

**出了什么问题？(What Happened?)**
<img width="645" alt="image" src="https://github.com/TencentBlueKing/bkui-vue3/assets/82189108/1ed6ccdc-d812-4fe7-b207-76e1d4780a53">

<img width="454" alt="image" src="https://github.com/TencentBlueKing/bkui-vue3/assets/82189108/932085f1-eea8-4af5-a6bc-8b1977c5e0f2">

**Comment by ielgnaw** [comment]
bkui-vue@1.0.3-beta.59
