### ISSUE TITLE
bugfix(pop-confirm): title 属性在 有 slot 的时候失效

### ISSUE THREAD

**Issue by forrany** [TencentBlueKing/bkui-vue3#1755]
**Version / Branch / tag**

**出了什么问题？(What Happened?)**

插槽导致 title 属性失效？

插槽应该是内容(content)的插槽，并不希望 title 失效

<img width="1272" alt="image" src="https://github.com/TencentBlueKing/bkui-vue3/assets/29779326/fc21eaa1-d836-435c-b091-84c3e540594c">

**如何复现？(How to reproduce?)**

**预期结果(What you expect?)**

**Comment by xiaolicheng-github** [comment]
https://github.com/TencentBlueKing/bkui-vue3/pull/1813
