### ISSUE TITLE
bugfix(pop-confirm): placement 属性不生效，无法将其放在下方 

### ISSUE THREAD

**Issue by forrany** [TencentBlueKing/bkui-vue3#1757]
**Version / Branch / tag**

**出了什么问题？(What Happened?)**
<img width="1580" alt="image" src="https://github.com/TencentBlueKing/bkui-vue3/assets/29779326/c67f7ae2-02e1-4be5-b6ab-3313357284e1">

**如何复现？(How to reproduce?)**

**预期结果(What you expect?)**

**Comment by xiaolicheng-github** [comment]
https://github.com/TencentBlueKing/bkui-vue3/pull/1868
