### ISSUE TITLE
bugfix(table): 表头过滤弹窗期望默认支持 '超出...' 的规范 

### ISSUE THREAD

**Issue by forrany** [TencentBlueKing/bkui-vue3#1759]
**Version / Branch / tag**

**出了什么问题？(What Happened?)**

<img width="1298" alt="image" src="https://github.com/TencentBlueKing/bkui-vue3/assets/29779326/af013ccb-2e07-4b69-a43b-552371b10ce5">

**如何复现？(How to reproduce?)**

**预期结果(What you expect?)**

**Comment by ielgnaw** [comment]
bkui-vue@2.0.1-beta.67
