### ISSUE TITLE
bugfix(time-picker): 添加`append-to-body`属性，选择后需要点击两次才能关闭 

### ISSUE THREAD

**Issue by forrany** [TencentBlueKing/bkui-vue3#1808]
**Version / Branch / tag**

**出了什么问题？(What Happened?)**

```vue
<template>
  <bk-time-picker
    v-model="dateValue"
    format="HH:mm"
    append-to-body
    clearable
  />
</template>

<script setup>
  import { ref } from 'vue';
  const dateValue = ref('12:12:12');
</script>

```

![iShot_2024-05-11_10 50 07](https://github.com/TencentBlueKing/bkui-vue3/assets/29779326/a0cede34-491a-47fc-ac86-d1936701a001)

**如何复现？(How to reproduce?)**

**预期结果(What you expect?)**

**Comment by lhzzforever** [comment]
Done
