### ISSUE TITLE
bugfix(time-picker): 使用键盘修改时间，UI上更改了，但是值没有变化 

### ISSUE THREAD

**Issue by forrany** [TencentBlueKing/bkui-vue3#1809]
**Version / Branch / tag**

**出了什么问题？(What Happened?)**

https://github.com/TencentBlueKing/bkui-vue3/assets/29779326/950fad98-ff06-49a9-847d-9d21e9d34692

**如何复现？(How to reproduce?)**

**预期结果(What you expect?)**

**Comment by ielgnaw** [comment]
bkui-vue@2.0.1-beta.58
