### ISSUE TITLE
feature: tab组件支持配置展示数字跟数字样式类型

### ISSUE THREAD

**Issue by terlinhe** [TencentBlueKing/bkui-vue3#1811]
tab-panel 支持num属性， 当tab-panel有值时， 展示数字
同时可支持设置数字的样式类型
<img width="715" alt="企业微信截图_926d68dc-5e25-46d0-bfee-f18c20cde14b" src="https://github.com/TencentBlueKing/bkui-vue3/assets/12457501/da310b14-8f35-43fe-855e-963f36a0b8ef">

**Comment by ielgnaw** [comment]
bkui-vue@2.0.1-beta.62
