### ISSUE TITLE
feature(table): 表格组件支持只显示表头区域的tooltips 

### ISSUE THREAD

**Issue by luofann** [TencentBlueKing/bkui-vue3#1833]
![image](https://github.com/TencentBlueKing/bkui-vue3/assets/44999219/f9b7c457-701e-40b0-a7d6-b3d5459c1f06)

![image](https://github.com/TencentBlueKing/bkui-vue3/assets/44999219/9242a5b9-1980-43b3-b45f-ed7eb6cc531e)

![image](https://github.com/TencentBlueKing/bkui-vue3/assets/44999219/f5affcba-4ada-4c3e-b63d-83b329988bcb)

目前只设置表头的tooltips后，表格数据区域也会有，hover上去的内容为空。

### 预期
希望能够增加配置只设置表头区域的tooltips，去掉表格内容区域的tooltips。

**Comment by ielgnaw** [comment]
bkui-vue@2.0.1-beta.58
