### ISSUE TITLE
bugfix(language cookie):  值统一

### ISSUE THREAD

**Issue by forrany** [TencentBlueKing/bkui-vue3#1863]
**Version / Branch / tag**

**出了什么问题？(What Happened?)**
<img width="1304" alt="image" src="https://github.com/TencentBlueKing/bkui-vue3/assets/29779326/e063039a-7790-463a-99e5-d481699abf3f">

期望统一各平台的该值
**如何复现？(How to reproduce?)**

**预期结果(What you expect?)**

**Comment by ielgnaw** [comment]
中文 `zh-cn`

英文 `en`
