### ISSUE TITLE
bugfix(date-picker): 选择日期范围时，交互异常

### ISSUE THREAD

**Issue by jinquantianxia** [TencentBlueKing/bkui-vue3#1912]
这是选之前的日期范围：
![image](https://github.com/TencentBlueKing/bkui-vue3/assets/22766131/159104e1-bb1c-41c2-b733-52d62a1c8376)
点击最左侧的年份切换图标后：
![image](https://github.com/TencentBlueKing/bkui-vue3/assets/22766131/0ad2af72-c07d-45c3-9252-e08cad6150d3)
预期应该是左边的年份减1年，其他的不变

**Comment by ielgnaw** [comment]
已修复

bkui-vue@2.0.1-beta.20
