### ISSUE TITLE
feature(dockerfile): 快速容器化部署调试资源，便于用户在研发测试环境进行调试 

### ISSUE THREAD

**Issue by ai-liuys** [TencentBlueKing/bkui-vue3#2044]
当前的资源代码更多的是基于本地环境启动运行，并且由于资源环境的限制需要下载前端相关的依赖并且需要控制版本才可以正常运行，对于非前端用户，并不是特别友好。
- 鉴于蓝鲸系统需要协同研发的需要；
- 简化非前端用户对于前端 UI 的学习成本;
- 便于前端 UI 库可以便于快速部署运维的需要;

新功能:  增加容器化镜像制作和快速部署的说明和代码调整进行开发。

**Comment by ielgnaw** [comment]
看你已经发了 pr，已 merge
