### ISSUE TITLE
bugfix(Pagination): 手动输入页码后点击上下页，页码未改变

### ISSUE THREAD

**Issue by useryuyu** [TencentBlueKing/bkui-vue3#2045]
![image](https://github.com/user-attachments/assets/1694819b-197f-4fc5-8e49-ca44255ff10a)
手动输入页码后，再次点击上一页或者下一页或者下拉选择页码，分页逻辑有调用，但是页码的数字未改变

**Comment by lhzzforever** [comment]
Done
