### ISSUE TITLE
feature(table): table组件表头筛选组件的筛选逻辑

### ISSUE THREAD

**Issue by JayCC1** [TencentBlueKing/bkui-vue3#2048]
在 table 中的表头筛选组件中的 input 框输入筛选查找filterList 中的 options 逻辑 ，目前的筛选逻辑是输入后根据option 的 value 去进行筛选，但是在数据是枚举类型数据时，则没办法使用。
且筛选是面向用户的，用户只能知晓并看到label的值并不知道实际选项对应的value是什么，所以在输入后筛选逻辑是否应该是根据option的label去进行筛选而不是value

场景：
1. 传入这种类型数据时
![image](https://github.com/user-attachments/assets/a882e912-9886-4f56-825d-6a5c43343dc7)

![image](https://github.com/user-attachments/assets/807a7052-4f38-4c84-b033-c52f8ff661b3)
![image](https://github.com/user-attachments/assets/08096b90-20b2-4f31-bd84-eb26ef6fcbbc)
![image](https://github.com/user-attachments/assets/94b8988a-2a02-4a53-9ab7-5b47beb34337)

**Comment by ielgnaw** [comment]
bkui-vue@2.0.1-beta.58
