### ISSUE TITLE
bugfix(table): 表头筛选选项少于5条时，高度没有自动撑开

### ISSUE THREAD

**Issue by 3octaves** [TencentBlueKing/bkui-vue3#2082]
**出了什么问题？(What Happened?)**
![image](https://github.com/user-attachments/assets/f33d185f-b0c2-427e-9fee-76ef554bfffd)

**预期结果(What you expect?)**
![image](https://github.com/user-attachments/assets/ef029d60-b1b7-4340-b01f-f7ea25410f4f)

似乎是因为这个height 100%没生效，按min height来显示高度了
![企业微信截图_17240632031998](https://github.com/user-attachments/assets/d2351e85-7320-4374-86e0-c0e308245ef2)
![企业微信截图_17240634456671](https://github.com/user-attachments/assets/288639f0-b142-4703-8263-835cb59880ec)

**Comment by ielgnaw** [comment]
bkui-vue@2.0.1-beta.58
