### ISSUE TITLE
bugfix(table): 点击行内radio或checkbox组件时row-click事件会触发两次

### ISSUE THREAD

**Issue by 3octaves** [TencentBlueKing/bkui-vue3#2104]
使用如下语句打印的控制台信息 console.log("bk-table row click", event.target) 

![image](https://github.com/user-attachments/assets/7addb06c-d044-4838-b0e3-12e8e09ad68b)
![image](https://github.com/user-attachments/assets/2064a985-3081-48bd-9462-86784cc33a5f)

**Comment by ielgnaw** [comment]
bkui-vue@2.0.1-beta.62
