### ISSUE TITLE
bugfix(): BkSearchSelect的max-height不生效

### ISSUE THREAD

**Issue by JustaCattt** [TencentBlueKing/bkui-vue3#2135]
![企业微信截图_17261099287669](https://github.com/user-attachments/assets/a9f901cd-7e41-43e2-9f53-98b632eed49a)这个组件的最大高度不明确是改哪个元素的最大高度啊。
![企业微信截图_17261099954488](https://github.com/user-attachments/assets/2f15a26a-1f3e-4750-921c-25880fae17fd)
我希望的这个高度可以展示12条(默认高度240px，所需高度392px才能展示12条)，但是pop是在body次级的，修改样式会污染全局，于是给BkSearchSelect设置max-height好像并没有什么实际变化

**Comment by ielgnaw** [comment]
2.0.1-beta.69
