### ISSUE TITLE
bugfix(table): 表格筛选选中失效

### ISSUE THREAD

**Issue by byronbyyuan** [TencentBlueKing/bkui-vue3#2141]
![image](https://github.com/user-attachments/assets/f94a0038-0862-4b86-97d9-81498d473878)

1. 当过滤器选中了数据后，返回的数据中 checkd已有选中数据，但是column中没有，一旦刷新表格数据后，筛选选中丢失(选中态缓存缓存在column的checkd中)

**Comment by ielgnaw** [comment]
bkui-vue@2.0.1-beta.70
