### ISSUE TITLE
bugfix(ColorPicker ): 可否支持一下选择颜色的popover能默认展开

### ISSUE THREAD

**Issue by w-beibei** [TencentBlueKing/bkui-vue3#2144]
**Version / Branch / tag**

**出了什么问题？(What Happened?)**

**如何复现？(How to reproduce?)**

**预期结果(What you expect?)**
希望像这样初始化时可以默认展开
![image](https://github.com/user-attachments/assets/6bf587fd-befc-4061-9462-396be0155742)

**Comment by ielgnaw** [comment]
bkui-vue@2.0.1-beta.70

showOnInit 属性

**Comment by w-beibei** [comment]
您好，您的邮件已经收到，谢谢!                                               王贝贝
