### ISSUE TITLE
feature(form表单): 1.表单校验，默认触发方式建议为change,不然每个校验都需要手动添加tigger:change。2.在表单级添加disable，所有输入项都disabled

### ISSUE THREAD

**Issue by wanglj-belink** [TencentBlueKing/bkui-vue3#2175]
1.<img width="443" alt="image" src="https://github.com/user-attachments/assets/55777366-8b7c-4c09-a423-0ce526dad2d9">
期望有输入后就触发
2.表单添加disabled属性：是否禁用该表单内的所有组件。 如果设置为 true, 它将覆盖内部组件的 disabled 属性

**Comment by ielgnaw** [comment]
现在就是输入后就触发

**Comment by wanglj-belink** [comment]
> 现在就是输入后就触发

不是的。现在是但凡需要输入就触发的，需要手动添加trigger: 'change'

**Comment by ielgnaw** [comment]
手动配一下 trigger: 'change'

现在再改这些默认配置影响较大
