### ISSUE TITLE
feature(bk-button-group): 按钮组每个按钮能否支持按钮主题呢？

### ISSUE THREAD

**Issue by wanglj-belink** [TencentBlueKing/bkui-vue3#2176]
<img width="542" alt="image" src="https://github.com/user-attachments/assets/c1cd051b-c981-4959-b538-dae8491ae652">
<img width="507" alt="image" src="https://github.com/user-attachments/assets/b64ebf38-17fb-4323-ac86-fd2f01b1c336">

**Comment by lhzzforever** [comment]
@wanglj-belink  这个是想默认就展示按钮主题色呢，还是选中展示主题色呢,  现在默认色和激活色都固定
