### ISSUE TITLE
bugfix(bk-sideslider): 高度计算问题

### ISSUE THREAD

**Issue by hLinx** [TencentBlueKing/bkui-vue3#382]
**Version / Branch / tag**

**出了什么问题？(What Happened?)**
<img width="670" alt="企业微信截图_784d998f-a6f9-47f3-827e-483b2dba6de5" src="https://user-images.githubusercontent.com/17508060/173522892-8f7867a3-ebce-4e55-9f3f-fff2e7ead698.png">

**如何复现？(How to reproduce?)**

**预期结果(What you expect?)**

`bk-modal-content`的高度在有 `footer`的时候只减去了`header`的高度`max-height: calc(100vh - 60px);`，应该同时要减去`footer`的高度

**Comment by caohua** [comment]
<img width="1191" alt="wecom-temp-4f9ba2e3b938a7b2d2456cfa85a93b74" src="https://user-images.githubusercontent.com/5043740/175020274-cb841abc-649e-4991-8243-5f4dd928dc5a.png">
