### ISSUE TITLE
feature(Table): table表格系列问题

### ISSUE THREAD

**Issue by zhoulujun** [TencentBlueKing/bkui-vue3#487]
## 表格对齐方式
添加可以设置单独列的对齐方式的设置
## 样式设置
高亮特定的行，单独的行样式设置、单元格样式
## 宽度设置
当设置最小宽度时，父容器盒子的宽度设置为所有列设置的最小宽度之和 显示不完全

**Comment by Lw2964709499** [comment]
> ## 表格对齐方式
> 添加可以设置单独列的对齐方式的设置
> 
> ## 宽度设置
> 当设置最小宽度时，父容器盒子的宽度设置为所有列设置的最小宽度之和 显示不完全
> 如图
![2022-07-20-11-11-33-image](https://user-images.githubusercontent.com/76611704/179893684-ebee13d8-b8da-48c6-b1e5-32ef51c519f4.png)
![2022-07-20-11-12-49-image](https://user-images.githubusercontent.com/76611704/179893700-c8e86284-8d86-49c9-a645-6a7943187b2e.png)
渲染出来的对不上 表格和父盒子的最小宽度均为1280
最小宽度加起来也是刚好1280 为什么渲染出来的却大于1280
我认为列最小宽度的配置的意思是：
pw(父组件的宽度) sum(列宽度之和,对于每一列 宽度优先级大于 最小宽度)
pw<=sum 则表格宽度应为 sum，每一列宽度为设置的值
pw>sum 则表格宽度为pw 如果该列设置width,则该列宽度为width，否则该列宽度为 $width= minWidth+剩余宽度/(minWidth 之和) * minWidth$
或者说
表格宽度即为父盒子宽度
若 pw<=sum 若设置了列宽度即为该值 反之 $width =（pw-(width之和)）*minWidth/(minWidth之和)$
若 pw>sum 第一种情况
可目前来看不是这样的
> ## 分页对齐，对齐方式可以设置（居左，居右，居中
