### ISSUE TITLE
feature(Document): 希望文档可以添加部分组件的 JSX 的示例

### ISSUE THREAD

**Issue by JJLau626** [TencentBlueKing/bkui-vue3#915]
比如：CheckBox 和 CheckBox-Group、Radio 和 Radio-Button/Group 这些组件，在 jsx 下的代码示例。如果只是通过文档查看会产生疑惑，最后还是得看声明文件才能看懂。
![image](https://user-images.githubusercontent.com/26458821/234824063-452e4b9e-4183-4874-bd04-f3ab13bb3846.png)

希望能和 AntD 类似

**Comment by ielgnaw** [comment]
@JJLau626 你好，咨询下使用场景，你是希望复制出来的代码直接放到项目中就可以使用是吗？

看其他组件库基本在提供的 template。AntD 这块的切换也只是切换 js 和 ts，模版这块没变化

https://www.antdv.com/components/input-cn

<img width="721" alt="image" src="https://github.com/TencentBlueKing/bkui-vue3/assets/1153430/f61ef2b8-4d51-443e-b1ea-9c6de70e6172">

**Comment by JJLau626** [comment]
> @JJLau626 你好，咨询下使用场景，你是希望复制出来的代码直接放到项目中就可以使用是吗？
> 
> 看其他组件库基本在提供的 template。AntD 这块的切换也只是切换 js 和 ts，模版这块没变化
> 
> https://www.antdv.com/components/input-cn
> 
> <img alt="image" width="721" src="https://user-images.githubusercontent.com/1153430/237618985-f61ef2b8-4d51-443e-b1ea-9c6de70e6172.png">

你好！
我的意思是希望能有一个 jsx 版本的文档，因为没有文档的辅助，可能不知道 jsx 项目下如何调用以上所提到的复选框组件。

**Comment by ielgnaw** [comment]
明白了 后面我们加上
